# Generated by Django 5.1.1 on 2024-11-06 18:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('tipo', models.CharField(default='General', max_length=45)),
                ('cuandoSeCultiva', models.CharField(max_length=45)),
                ('cuidados', models.CharField(max_length=100)),
                ('comentarios', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Resumen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('dispositivo', models.CharField(default='pordefecto', max_length=45)),
                ('luz', models.FloatField(default=0.0)),
                ('humedad', models.FloatField(default=0.0)),
                ('temperatura', models.FloatField(default=25.0)),
                ('humedadSuelo', models.FloatField(default=0.0)),
                ('rendimiento', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('humedadSuelo_min', models.FloatField(default=0.0)),
                ('humedadSuelo_max', models.FloatField(default=0.0)),
                ('humedadAmbiente_min', models.FloatField(default=0.0)),
                ('humedadAmbiente_max', models.FloatField(default=0.0)),
                ('temperaturaAmbiente_min', models.FloatField(default=0.0)),
                ('temperaturaAmbiente_max', models.FloatField(default=40.0)),
                ('luminiscencia_min', models.FloatField(default=0.0)),
                ('luminiscencia_max', models.FloatField(default=100.0)),
                ('cultivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='params', to='cultivos.cultivo')),
            ],
        ),
    ]
